# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/Infinix/X626/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/Infinix/X626/proprietary/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/Infinix/X626/proprietary/etc/init/kpoc_charger.rc:system/etc/init/kpoc_charger.rc \
    vendor/Infinix/X626/proprietary/lib/libgraphics2d_ext.so:system/lib/libgraphics2d_ext.so \
    vendor/Infinix/X626/proprietary/lib/libmtkaudio_utils.so:system/lib/libmtkaudio_utils.so \
    vendor/Infinix/X626/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/Infinix/X626/proprietary/lib/libsysenv_system.so:system/lib/libsysenv_system.so
